package main

import (
	"fmt"
	"time"
)

// generateManPage returns a roff-formatted man page suitable for
// piping to "man -l -" or saving to a file.
func generateManPage() string {
	buildDate := date
	if buildDate == "unknown" {
		buildDate = time.Now().Format("2006-01-02")
	}

	return fmt.Sprintf(`.\" Granit man page — generated by granit man
.TH GRANIT 1 "%s" "Granit %s" "User Commands"

.SH NAME
granit \- terminal knowledge manager (Obsidian compatible)

.SH SYNOPSIS
.B granit
.RI [ vault-path ]
.br
.B granit
.I command
.RI [ arguments ]

.SH DESCRIPTION
.B Granit
is a terminal-based knowledge management application, compatible with
Obsidian vaults. It provides a rich TUI for editing, linking, and
organizing Markdown notes with features including wikilink navigation,
backlink tracking, graph visualization, AI-powered analysis, a canvas
whiteboard, calendar integration, and a plugin system.
.PP
When launched without arguments,
.B granit
shows a vault selector if vaults have been previously opened, or opens
the current directory as a vault. When given a directory path, it opens
that path directly as a vault.

.SH COMMANDS

.SS Core
.TP
.B open \fIpath\fR
Open the vault at
.I path
in the TUI.
.TP
.B daily \fR[\fIpath\fR]
Create or open today's daily note. If
.I path
is omitted, the current directory is used.
.TP
.B today \fR[\fIpath\fR]
Print today's terminal dashboard: tasks, overdue items, upcoming
(7 days), and habit streaks. Use \fB\-\-json\fR for JSON output.
.TP
.B review \fR[\fIpath\fR]
Generate a daily review summary. Use \fB\-\-week\fR for weekly.
\fB\-\-markdown\fR outputs sendable markdown. \fB\-\-save\fR writes
the review to the Reviews/ folder in the vault.
.TP
.B todo \fItext\fR
Add a task to Tasks.md. Supports \fB\-\-due\fR (today, tomorrow,
monday, YYYY-MM-DD), \fB\-\-priority\fR (highest, high, medium, low),
and \fB\-\-tag\fR.
.TP
.B sync \fR[\fIpath\fR]
Pull (rebase), stage all changes, commit, and push in one command.
Auto-resolves conflicts by accepting the newest version.
Supports \fB\-\-quiet\fR, \fB\-\-dry\-run\fR, and \fB\-m\fR.
.TP
.B clock in \fR[\fB\-\-project \fIname\fR]
Start a work session. The elapsed time is shown in the TUI status bar.
.TP
.B clock out
End the active session. The session is logged to Timetracking/ in the vault.
.TP
.B clock status
Show the current session status and today's total time.
.TP
.B clock log \fR[\fB\-\-week\fR]
Show today's time log, or the weekly summary with \fB\-\-week\fR.
.TP
.B remind \fItext\fR \fB\-\-at \fIHH:MM\fR
Set a reminder. Use \fB\-\-daily\fR (default), \fB\-\-weekdays\fR, or \fB\-\-once\fR.
Reminders fire as a terminal bell and status bar notification in the TUI.
.TP
.B remind list
Show all configured reminders.
.TP
.B remind remove \fInumber\fR
Remove a reminder by its index.
.TP
.B completion \fR<\fIbash\fR|\fIzsh\fR|\fIfish\fR>
Output shell completion script for the given shell.
.TP
.B help\fR, \fB\-\-help\fR, \fB\-h
Display the help summary and exit.
.TP
.B version\fR, \fB\-\-version\fR, \fB\-v
Print version information and exit.

.SS Vault Management
.TP
.B init \fR[\fIpath\fR]
Initialize a new vault at the given path (default: current directory).
Creates the directory and initial configuration.
.TP
.B scan \fIpath\fR
Scan the vault at
.I path
and print statistics including note count, frontmatter, links, and
backlinks. Supports \fB\-\-json\fR and \fB\-\-compact\fR.
.TP
.B list \fR[\fB\-\-vaults\fR|\fB\-\-json\fR|\fB\-\-paths\fR|\fB\-\-tags\fR]
List all known vaults or vault notes with filtering options.
The last-used vault is marked with an asterisk.
.TP
.B config
Display configuration file paths and the current effective settings
as JSON.
.TP
.B search \fIquery\fR \fR[\fIpath\fR]
Search vault content with colored output.
Supports \fB\-\-regex\fR, \fB\-\-json\fR, \fB\-\-case\-sensitive\fR.
.TP
.B query \fR'\fIexpression\fR' \fR[\fIpath\fR]
Query notes by metadata. Supports \fB\-\-json\fR and \fB\-\-table\fR.
.TP
.B backup \fR[\fIpath\fR]
Create a timestamped zip backup of the vault.
Supports \fB\-\-output\fR, \fB\-\-restore \fIfile\fR, and \fB\-\-list\fR.
.TP
.B serve \fR[\fIpath\fR] [\fB\-\-port \fIN\fR]
Serve vault as a read-only website. Default port: 8080.
.TP
.B import \fB\-\-from \fIformat\fR \fIsrc\fR
Import from Obsidian, Logseq, or Notion vaults.
.TP
.B export \fR[\fIpath\fR]
Export vault notes. Supports \fB\-\-format\fR (html/text/json),
\fB\-\-output\fR, \fB\-\-all\fR, \fB\-\-note\fR.

.SS Data Capture
.TP
.B capture \fR[\fItext\fR]
Quick-capture to inbox.md with timestamp.
Supports \fB\-v/\-\-vault\fR and \fB\-f/\-\-file\fR.
.TP
.B clip
Capture from stdin to inbox.md.
Example: \fBecho "idea" | granit clip\fR.
Supports \fB\-v/\-\-vault\fR and \fB\-f/\-\-file\fR.

.SS Plugin Management
.TP
.B plugin list
List all installed plugins.
.TP
.B plugin install \fIpath\fR
Install a plugin from a local directory.
.TP
.B plugin remove \fIname\fR
Remove an installed plugin.
.TP
.B plugin enable \fIname\fR
Enable a plugin.
.TP
.B plugin disable \fIname\fR
Disable a plugin.
.TP
.B plugin info \fIname\fR
Show detailed plugin information. Supports \fB\-\-json\fR.
.TP
.B plugin create \fIname\fR
Scaffold a new plugin template. Supports \fB\-\-dir=\fIpath\fR.

.SS Advanced
.TP
.B man
Output this man page in roff format. Pipe to
.BR man (1)
for formatted viewing:
.RS
.nf
granit man | man -l -
.fi
.RE

.SH KEYBOARD SHORTCUTS

.SS Navigation
.TP
.B Tab / Shift+Tab
Cycle between panels (sidebar, editor, backlinks).
.TP
.B F1
Focus file sidebar.
.TP
.B F2
Focus editor.
.TP
.B F3
Focus backlinks panel.
.TP
.B j/k \fRor\fB Up/Down
Navigate lists.
.TP
.B Enter
Open selected file or follow link.
.TP
.B PgUp / PgDn
Scroll page up or down.
.TP
.B Type to search
Fuzzy filter in sidebar.

.SS Editing
.TP
.B Ctrl+S
Save current note.
.TP
.B Ctrl+E
Toggle between view and edit mode.
.TP
.B Ctrl+U
Undo.
.TP
.B Ctrl+Y
Redo.
.TP
.B Ctrl+F
Find in file.
.TP
.B Ctrl+H
Find and replace.
.TP
.B Ctrl+D
Multi-cursor: select word under cursor, then add next occurrence.
.TP
.B Ctrl+Shift+Up/Down
Add cursor above or below.

.SS Overlays
.TP
.B Ctrl+P
Quick open (fuzzy file search).
.TP
.B Ctrl+N
Create new note with template picker.
.TP
.B Ctrl+J
Quick switch between open files.
.TP
.B Ctrl+O
Note outline (heading navigation).
.TP
.B Ctrl+B
Bookmarks and recent notes.
.TP
.B Ctrl+G
Note graph visualization.
.TP
.B Ctrl+T
Browse tags.
.TP
.B Ctrl+W
Canvas / whiteboard.
.TP
.B Ctrl+L
Calendar with month, week, and agenda views.
.TP
.B Ctrl+X
Command palette.
.TP
.B Ctrl+,
Settings overlay.
.TP
.B F4
Rename current note.
.TP
.B F5
Show keyboard shortcuts.
.TP
.B Ctrl+Z
Focus / zen mode (distraction-free writing).
.TP
.B Esc
Close overlay or return to sidebar.

.SS AI Bots
.TP
.B Ctrl+R
Open AI bots panel. Supports Ollama, OpenAI, and local fallback
providers. Nine built-in bots: Auto-Tagger, Link Suggester,
Summarizer, Question Bot, Writing Assistant, Title Suggester,
Action Items, MOC Generator, and Daily Digest.

.SS Application
.TP
.B Ctrl+Q\fR, \fBCtrl+C
Quit the application.

.SH LAYOUTS
.B Granit
supports eight layout modes, configurable via settings or the
command palette:
.TP
.B default
Three-panel layout: sidebar, editor, and backlinks.
.TP
.B writer
Two-panel layout: sidebar and editor.
.TP
.B minimal
Editor only; full-screen writing.
.TP
.B reading
Two-panel layout: editor and backlinks (wide reading).
.TP
.B dashboard
Four-panel layout: sidebar, editor, outline, and backlinks.
.TP
.B zen
Centered editor, 80-char max width, no chrome.
.TP
.B taskboard
Three-panel layout: sidebar, editor, and task summary.
.TP
.B research
Three-panel layout: sidebar, editor, and notes/backlinks panel.
.PP
The layout adapts automatically on narrow terminals (below 80
columns switches to minimal, below 120 to writer).

.SH THEMES
35 built-in themes are available (29 dark + 6 light), switchable at
runtime via Ctrl+, (settings) or the command palette. Custom themes
can be created with the built-in Theme Editor.
.PP
catppuccin-mocha, catppuccin-latte, catppuccin-frappe,
catppuccin-macchiato, tokyo-night, gruvbox-dark, nord, dracula,
solarized-dark, solarized-light, rose-pine, rose-pine-dawn,
everforest-dark, kanagawa, one-dark, github-dark, github-light,
ayu-dark, ayu-light, palenight, synthwave-84, nightfox, vesper,
poimandres, moonlight, vitesse-dark, min-light, oxocarbon,
matrix, cobalt2, monokai-pro, horizon, zenburn, iceberg, amber.

.SH PLUGINS
Plugins are scripts invoked by
.B granit
at defined hook points. They reside in:
.TP
.I ~/.config/granit/plugins/<name>/
Global plugins available to all vaults.
.TP
.I <vault>/.granit/plugins/<name>/
Vault-local plugins.
.PP
Each plugin has a
.B plugin.json
manifest defining its name, version, commands, and hooks
.RB ( on_save ", " on_open ", " on_create ", " on_delete ).
Scripts receive environment variables
.RB ( GRANIT_NOTE_PATH ", " GRANIT_NOTE_NAME ", " GRANIT_VAULT_PATH )
and note content via stdin. Output prefixes:
.BR MSG: " (status message),"
.BR CONTENT: " (base64-encoded replacement content),"
.BR INSERT: " (base64-encoded text to insert)."
A 10-second execution timeout is enforced.

.SH FILES
.TP
.I ~/.config/granit/config.json
Global configuration file (JSON). Controls theme, editor settings,
AI provider, layout, and all other preferences.
.TP
.I ~/.config/granit/vaults.json
Registry of known vaults with paths, names, and last-opened dates.
.TP
.I <vault>/.granit.json
Per-vault configuration overrides. Settings here take precedence
over the global config.
.TP
.I ~/.config/granit/plugins/
Global plugin directory.
.TP
.I <vault>/.granit/plugins/
Per-vault plugin directory.
.TP
.I <vault>/.granit/clock.json
Active clock session and time tracking history.
.TP
.I <vault>/.granit/reminders.json
Configured reminders with schedules and patterns.
.TP
.I <vault>/Timetracking/
Daily time log markdown files generated by clock out.
.TP
.I <vault>/.granit-trash/
Recycle bin for deleted notes (restorable via the trash overlay).

.SH ENVIRONMENT
.TP
.B GRANIT_VAULT
Default vault path. When set and no path is provided on the command
line, this vault is opened automatically.
.TP
.B EDITOR
Preferred external editor. Used when shelling out to edit files.

.SH AUTHORS
.B Granit
is developed by Artaeon <raphael.lugmayr@stoicera.com>.

.SH SEE ALSO
.BR obsidian (1),
.BR vim (1),
.BR nvim (1)

.SH BUGS
Report issues at: https://github.com/artaeon/granit/issues
`, buildDate, version)
}
