package main

import (
	"fmt"
	"time"
)

// generateManPage returns a roff-formatted man page suitable for
// piping to "man -l -" or saving to a file.
func generateManPage() string {
	buildDate := date
	if buildDate == "unknown" {
		buildDate = time.Now().Format("2006-01-02")
	}

	return fmt.Sprintf(`.\" Granit man page — generated by granit man
.TH GRANIT 1 "%s" "Granit %s" "User Commands"

.SH NAME
granit \- terminal knowledge manager (Obsidian compatible)

.SH SYNOPSIS
.B granit
.RI [ vault-path ]
.br
.B granit
.I command
.RI [ arguments ]

.SH DESCRIPTION
.B Granit
is a terminal-based knowledge management application, compatible with
Obsidian vaults. It provides a rich TUI for editing, linking, and
organizing Markdown notes with features including wikilink navigation,
backlink tracking, graph visualization, AI-powered analysis, a canvas
whiteboard, calendar integration, and a plugin system.
.PP
When launched without arguments,
.B granit
shows a vault selector if vaults have been previously opened, or opens
the current directory as a vault. When given a directory path, it opens
that path directly as a vault.

.SH COMMANDS

.SS Core
.TP
.B open \fIpath\fR
Open the vault at
.I path
in the TUI.
.TP
.B daily \fR[\fIpath\fR]
Create or open today's daily note. If
.I path
is omitted, the current directory is used.
.TP
.B help\fR, \fB\-\-help\fR, \fB\-h
Display the help summary and exit.
.TP
.B version\fR, \fB\-\-version\fR, \fB\-v
Print version information and exit.

.SS Vault Management
.TP
.B scan \fIpath\fR
Scan the vault at
.I path
and print statistics including note count, frontmatter, links, and
backlinks.
.TP
.B list
List all known vaults with their names, paths, and last-opened dates.
The last-used vault is marked with an asterisk.
.TP
.B config
Display configuration file paths and the current effective settings
as JSON.

.SS Advanced
.TP
.B man
Output this man page in roff format. Pipe to
.BR man (1)
for formatted viewing:
.RS
.nf
granit man | man -l -
.fi
.RE

.SH KEYBOARD SHORTCUTS

.SS Navigation
.TP
.B Tab / Shift+Tab
Cycle between panels (sidebar, editor, backlinks).
.TP
.B F1
Focus file sidebar.
.TP
.B F2
Focus editor.
.TP
.B F3
Focus backlinks panel.
.TP
.B j/k \fRor\fB Up/Down
Navigate lists.
.TP
.B Enter
Open selected file or follow link.
.TP
.B PgUp / PgDn
Scroll page up or down.
.TP
.B Type to search
Fuzzy filter in sidebar.

.SS Editing
.TP
.B Ctrl+S
Save current note.
.TP
.B Ctrl+E
Toggle between view and edit mode.
.TP
.B Ctrl+U
Undo.
.TP
.B Ctrl+Y
Redo.
.TP
.B Ctrl+F
Find in file.
.TP
.B Ctrl+H
Find and replace.
.TP
.B Ctrl+D
Multi-cursor: select word under cursor, then add next occurrence.
.TP
.B Ctrl+Shift+Up/Down
Add cursor above or below.

.SS Overlays
.TP
.B Ctrl+P
Quick open (fuzzy file search).
.TP
.B Ctrl+N
Create new note with template picker.
.TP
.B Ctrl+J
Quick switch between open files.
.TP
.B Ctrl+O
Note outline (heading navigation).
.TP
.B Ctrl+B
Bookmarks and recent notes.
.TP
.B Ctrl+G
Note graph visualization.
.TP
.B Ctrl+T
Browse tags.
.TP
.B Ctrl+W
Canvas / whiteboard.
.TP
.B Ctrl+L
Calendar with month, week, and agenda views.
.TP
.B Ctrl+X
Command palette.
.TP
.B Ctrl+,
Settings overlay.
.TP
.B F4
Rename current note.
.TP
.B F5
Show keyboard shortcuts.
.TP
.B Ctrl+Z
Focus / zen mode (distraction-free writing).
.TP
.B Esc
Close overlay or return to sidebar.

.SS AI Bots
.TP
.B Ctrl+R
Open AI bots panel. Supports Ollama, OpenAI, and local fallback
providers. Nine built-in bots: Auto-Tagger, Link Suggester,
Summarizer, Question Bot, Writing Assistant, Title Suggester,
Action Items, MOC Generator, and Daily Digest.

.SS Application
.TP
.B Ctrl+Q\fR, \fBCtrl+C
Quit the application.

.SH LAYOUTS
.B Granit
supports three layout modes, configurable via settings or the
command palette:
.TP
.B default
Three-panel layout: sidebar, editor, and backlinks.
.TP
.B writer
Two-panel layout: sidebar and editor.
.TP
.B minimal
Editor only; full-screen writing.
.PP
The layout adapts automatically on narrow terminals (below 80
columns switches to minimal, below 120 to writer).

.SH THEMES
28 built-in themes are available, switchable at runtime via Ctrl+,
(settings) or the command palette:
.PP
catppuccin-mocha, catppuccin-latte, catppuccin-frappe,
catppuccin-macchiato, tokyo-night, gruvbox-dark, nord, dracula,
solarized-dark, solarized-light, rose-pine, rose-pine-dawn,
everforest-dark, kanagawa, one-dark, github-dark, github-light,
ayu-dark, ayu-light, palenight, synthwave-84, nightfox, vesper,
poimandres, moonlight, vitesse-dark, min-light, oxocarbon.

.SH PLUGINS
Plugins are scripts invoked by
.B granit
at defined hook points. They reside in:
.TP
.I ~/.config/granit/plugins/<name>/
Global plugins available to all vaults.
.TP
.I <vault>/.granit/plugins/<name>/
Vault-local plugins.
.PP
Each plugin has a
.B plugin.json
manifest defining its name, version, commands, and hooks
.RB ( on_save ", " on_open ", " on_create ", " on_delete ).
Scripts receive environment variables
.RB ( GRANIT_NOTE_PATH ", " GRANIT_NOTE_NAME ", " GRANIT_VAULT_PATH )
and note content via stdin. Output prefixes:
.BR MSG: " (status message),"
.BR CONTENT: " (base64-encoded replacement content),"
.BR INSERT: " (base64-encoded text to insert)."
A 10-second execution timeout is enforced.

.SH FILES
.TP
.I ~/.config/granit/config.json
Global configuration file (JSON). Controls theme, editor settings,
AI provider, layout, and all other preferences.
.TP
.I ~/.config/granit/vaults.json
Registry of known vaults with paths, names, and last-opened dates.
.TP
.I <vault>/.granit.json
Per-vault configuration overrides. Settings here take precedence
over the global config.
.TP
.I ~/.config/granit/plugins/
Global plugin directory.
.TP
.I <vault>/.granit/plugins/
Per-vault plugin directory.
.TP
.I <vault>/.granit-trash/
Recycle bin for deleted notes (restorable via the trash overlay).

.SH ENVIRONMENT
.TP
.B GRANIT_VAULT
Default vault path. When set and no path is provided on the command
line, this vault is opened automatically.
.TP
.B EDITOR
Preferred external editor. Used when shelling out to edit files.

.SH AUTHORS
.B Granit
is developed by Artaeon <raphael.lugmayr@stoicera.com>.

.SH SEE ALSO
.BR obsidian (1),
.BR vim (1),
.BR nvim (1)

.SH BUGS
Report issues at: https://github.com/artaeon/granit/issues
`, buildDate, version)
}
