// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecent(arg1) {
  return window['go']['main']['GranitApp']['AddRecent'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['GranitApp']['CreateFolder'](arg1);
}

export function CreateFromTemplate(arg1, arg2) {
  return window['go']['main']['GranitApp']['CreateFromTemplate'](arg1, arg2);
}

export function CreateNote(arg1, arg2) {
  return window['go']['main']['GranitApp']['CreateNote'](arg1, arg2);
}

export function DeleteNote(arg1) {
  return window['go']['main']['GranitApp']['DeleteNote'](arg1);
}

export function ExportAll() {
  return window['go']['main']['GranitApp']['ExportAll']();
}

export function ExportHTML(arg1) {
  return window['go']['main']['GranitApp']['ExportHTML'](arg1);
}

export function ExportPDF(arg1) {
  return window['go']['main']['GranitApp']['ExportPDF'](arg1);
}

export function ExportText(arg1) {
  return window['go']['main']['GranitApp']['ExportText'](arg1);
}

export function GetAllSettings() {
  return window['go']['main']['GranitApp']['GetAllSettings']();
}

export function GetAllTags() {
  return window['go']['main']['GranitApp']['GetAllTags']();
}

export function GetBacklinkContext(arg1) {
  return window['go']['main']['GranitApp']['GetBacklinkContext'](arg1);
}

export function GetBookmarks() {
  return window['go']['main']['GranitApp']['GetBookmarks']();
}

export function GetBotList() {
  return window['go']['main']['GranitApp']['GetBotList']();
}

export function GetCalendarData(arg1, arg2) {
  return window['go']['main']['GranitApp']['GetCalendarData'](arg1, arg2);
}

export function GetCommands() {
  return window['go']['main']['GranitApp']['GetCommands']();
}

export function GetFolderTree() {
  return window['go']['main']['GranitApp']['GetFolderTree']();
}

export function GetGitBranch() {
  return window['go']['main']['GranitApp']['GetGitBranch']();
}

export function GetGraphData(arg1) {
  return window['go']['main']['GranitApp']['GetGraphData'](arg1);
}

export function GetKnownVaults() {
  return window['go']['main']['GranitApp']['GetKnownVaults']();
}

export function GetNote(arg1) {
  return window['go']['main']['GranitApp']['GetNote'](arg1);
}

export function GetNotes() {
  return window['go']['main']['GranitApp']['GetNotes']();
}

export function GetNotesForTag(arg1) {
  return window['go']['main']['GranitApp']['GetNotesForTag'](arg1);
}

export function GetOutline(arg1) {
  return window['go']['main']['GranitApp']['GetOutline'](arg1);
}

export function GetPlatform() {
  return window['go']['main']['GranitApp']['GetPlatform']();
}

export function GetTemplates() {
  return window['go']['main']['GranitApp']['GetTemplates']();
}

export function GetTheme() {
  return window['go']['main']['GranitApp']['GetTheme']();
}

export function GetTrashItems() {
  return window['go']['main']['GranitApp']['GetTrashItems']();
}

export function GetVaultPath() {
  return window['go']['main']['GranitApp']['GetVaultPath']();
}

export function GetVaultStats() {
  return window['go']['main']['GranitApp']['GetVaultStats']();
}

export function GitCommit(arg1) {
  return window['go']['main']['GranitApp']['GitCommit'](arg1);
}

export function GitDiff() {
  return window['go']['main']['GranitApp']['GitDiff']();
}

export function GitLog() {
  return window['go']['main']['GranitApp']['GitLog']();
}

export function GitPull() {
  return window['go']['main']['GranitApp']['GitPull']();
}

export function GitPush() {
  return window['go']['main']['GranitApp']['GitPush']();
}

export function GitStatus() {
  return window['go']['main']['GranitApp']['GitStatus']();
}

export function IsVaultOpen() {
  return window['go']['main']['GranitApp']['IsVaultOpen']();
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['GranitApp']['MoveFile'](arg1, arg2);
}

export function OpenVault(arg1) {
  return window['go']['main']['GranitApp']['OpenVault'](arg1);
}

export function PurgeFromTrash(arg1) {
  return window['go']['main']['GranitApp']['PurgeFromTrash'](arg1);
}

export function RefreshVault() {
  return window['go']['main']['GranitApp']['RefreshVault']();
}

export function RenameNote(arg1, arg2) {
  return window['go']['main']['GranitApp']['RenameNote'](arg1, arg2);
}

export function RestoreFromTrash(arg1) {
  return window['go']['main']['GranitApp']['RestoreFromTrash'](arg1);
}

export function RunBot(arg1, arg2, arg3) {
  return window['go']['main']['GranitApp']['RunBot'](arg1, arg2, arg3);
}

export function SaveNote(arg1, arg2) {
  return window['go']['main']['GranitApp']['SaveNote'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['main']['GranitApp']['Search'](arg1);
}

export function SelectVaultDialog() {
  return window['go']['main']['GranitApp']['SelectVaultDialog']();
}

export function SetTheme(arg1) {
  return window['go']['main']['GranitApp']['SetTheme'](arg1);
}

export function ToggleBookmark(arg1) {
  return window['go']['main']['GranitApp']['ToggleBookmark'](arg1);
}

export function ToggleTask(arg1, arg2) {
  return window['go']['main']['GranitApp']['ToggleTask'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['GranitApp']['UpdateSetting'](arg1, arg2);
}
