// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecent(arg1) {
  return window['go']['main']['GranitApp']['AddRecent'](arg1);
}

export function ChatWithAI(arg1) {
  return window['go']['main']['GranitApp']['ChatWithAI'](arg1);
}

export function CreateBackup() {
  return window['go']['main']['GranitApp']['CreateBackup']();
}

export function CreateFolder(arg1) {
  return window['go']['main']['GranitApp']['CreateFolder'](arg1);
}

export function CreateFromTemplate(arg1, arg2) {
  return window['go']['main']['GranitApp']['CreateFromTemplate'](arg1, arg2);
}

export function CreateNote(arg1, arg2) {
  return window['go']['main']['GranitApp']['CreateNote'](arg1, arg2);
}

export function CreateProject(arg1) {
  return window['go']['main']['GranitApp']['CreateProject'](arg1);
}

export function DecryptNote(arg1, arg2) {
  return window['go']['main']['GranitApp']['DecryptNote'](arg1, arg2);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['GranitApp']['DeleteBackup'](arg1);
}

export function DeleteCanvas(arg1) {
  return window['go']['main']['GranitApp']['DeleteCanvas'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['GranitApp']['DeleteNote'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['GranitApp']['DeleteProject'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['GranitApp']['DeleteWorkspace'](arg1);
}

export function EncryptNote(arg1, arg2) {
  return window['go']['main']['GranitApp']['EncryptNote'](arg1, arg2);
}

export function EnsureJournalNote(arg1) {
  return window['go']['main']['GranitApp']['EnsureJournalNote'](arg1);
}

export function ExportAll() {
  return window['go']['main']['GranitApp']['ExportAll']();
}

export function ExportHTML(arg1) {
  return window['go']['main']['GranitApp']['ExportHTML'](arg1);
}

export function ExportPDF(arg1) {
  return window['go']['main']['GranitApp']['ExportPDF'](arg1);
}

export function ExportText(arg1) {
  return window['go']['main']['GranitApp']['ExportText'](arg1);
}

export function GetAllSettings() {
  return window['go']['main']['GranitApp']['GetAllSettings']();
}

export function GetAllTags() {
  return window['go']['main']['GranitApp']['GetAllTags']();
}

export function GetAllTasks() {
  return window['go']['main']['GranitApp']['GetAllTasks']();
}

export function GetAutoLinkSuggestions(arg1) {
  return window['go']['main']['GranitApp']['GetAutoLinkSuggestions'](arg1);
}

export function GetBacklinkContext(arg1) {
  return window['go']['main']['GranitApp']['GetBacklinkContext'](arg1);
}

export function GetBookmarks() {
  return window['go']['main']['GranitApp']['GetBookmarks']();
}

export function GetBotList() {
  return window['go']['main']['GranitApp']['GetBotList']();
}

export function GetCalendarData(arg1, arg2) {
  return window['go']['main']['GranitApp']['GetCalendarData'](arg1, arg2);
}

export function GetCanvas(arg1) {
  return window['go']['main']['GranitApp']['GetCanvas'](arg1);
}

export function GetCommands() {
  return window['go']['main']['GranitApp']['GetCommands']();
}

export function GetDailyBriefing() {
  return window['go']['main']['GranitApp']['GetDailyBriefing']();
}

export function GetFlashcardProgress() {
  return window['go']['main']['GranitApp']['GetFlashcardProgress']();
}

export function GetFlashcards(arg1) {
  return window['go']['main']['GranitApp']['GetFlashcards'](arg1);
}

export function GetFolderTree() {
  return window['go']['main']['GranitApp']['GetFolderTree']();
}

export function GetGitBranch() {
  return window['go']['main']['GranitApp']['GetGitBranch']();
}

export function GetGraphData(arg1) {
  return window['go']['main']['GranitApp']['GetGraphData'](arg1);
}

export function GetHabits() {
  return window['go']['main']['GranitApp']['GetHabits']();
}

export function GetJournalNotes(arg1) {
  return window['go']['main']['GranitApp']['GetJournalNotes'](arg1);
}

export function GetJournalPrompts() {
  return window['go']['main']['GranitApp']['GetJournalPrompts']();
}

export function GetKanban() {
  return window['go']['main']['GranitApp']['GetKanban']();
}

export function GetKnownVaults() {
  return window['go']['main']['GranitApp']['GetKnownVaults']();
}

export function GetMindMapData(arg1) {
  return window['go']['main']['GranitApp']['GetMindMapData'](arg1);
}

export function GetNote(arg1) {
  return window['go']['main']['GranitApp']['GetNote'](arg1);
}

export function GetNoteAtVersion(arg1, arg2) {
  return window['go']['main']['GranitApp']['GetNoteAtVersion'](arg1, arg2);
}

export function GetNoteDiff(arg1, arg2) {
  return window['go']['main']['GranitApp']['GetNoteDiff'](arg1, arg2);
}

export function GetNoteHistory(arg1) {
  return window['go']['main']['GranitApp']['GetNoteHistory'](arg1);
}

export function GetNotes() {
  return window['go']['main']['GranitApp']['GetNotes']();
}

export function GetNotesForTag(arg1) {
  return window['go']['main']['GranitApp']['GetNotesForTag'](arg1);
}

export function GetOutline(arg1) {
  return window['go']['main']['GranitApp']['GetOutline'](arg1);
}

export function GetPlatform() {
  return window['go']['main']['GranitApp']['GetPlatform']();
}

export function GetPlugins() {
  return window['go']['main']['GranitApp']['GetPlugins']();
}

export function GetProjectTasks(arg1) {
  return window['go']['main']['GranitApp']['GetProjectTasks'](arg1);
}

export function GetProjects() {
  return window['go']['main']['GranitApp']['GetProjects']();
}

export function GetQuizQuestions(arg1) {
  return window['go']['main']['GranitApp']['GetQuizQuestions'](arg1);
}

export function GetRecurringTasks() {
  return window['go']['main']['GranitApp']['GetRecurringTasks']();
}

export function GetSmartConnections(arg1) {
  return window['go']['main']['GranitApp']['GetSmartConnections'](arg1);
}

export function GetSnippets() {
  return window['go']['main']['GranitApp']['GetSnippets']();
}

export function GetTemplates() {
  return window['go']['main']['GranitApp']['GetTemplates']();
}

export function GetTheme() {
  return window['go']['main']['GranitApp']['GetTheme']();
}

export function GetTimeline() {
  return window['go']['main']['GranitApp']['GetTimeline']();
}

export function GetTrashItems() {
  return window['go']['main']['GranitApp']['GetTrashItems']();
}

export function GetVaultPath() {
  return window['go']['main']['GranitApp']['GetVaultPath']();
}

export function GetVaultStats() {
  return window['go']['main']['GranitApp']['GetVaultStats']();
}

export function GetWritingFeedback(arg1) {
  return window['go']['main']['GranitApp']['GetWritingFeedback'](arg1);
}

export function GitCommit(arg1) {
  return window['go']['main']['GranitApp']['GitCommit'](arg1);
}

export function GitDiff() {
  return window['go']['main']['GranitApp']['GitDiff']();
}

export function GitLog() {
  return window['go']['main']['GranitApp']['GitLog']();
}

export function GitPull() {
  return window['go']['main']['GranitApp']['GitPull']();
}

export function GitPush() {
  return window['go']['main']['GranitApp']['GitPush']();
}

export function GitStatus() {
  return window['go']['main']['GranitApp']['GitStatus']();
}

export function IsNoteEncrypted(arg1) {
  return window['go']['main']['GranitApp']['IsNoteEncrypted'](arg1);
}

export function IsVaultOpen() {
  return window['go']['main']['GranitApp']['IsVaultOpen']();
}

export function ListBackups() {
  return window['go']['main']['GranitApp']['ListBackups']();
}

export function ListCanvases() {
  return window['go']['main']['GranitApp']['ListCanvases']();
}

export function ListWorkspaces() {
  return window['go']['main']['GranitApp']['ListWorkspaces']();
}

export function LoadWorkspace(arg1) {
  return window['go']['main']['GranitApp']['LoadWorkspace'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['GranitApp']['MoveFile'](arg1, arg2);
}

export function OpenVault(arg1) {
  return window['go']['main']['GranitApp']['OpenVault'](arg1);
}

export function ParseMarkdownTable(arg1, arg2) {
  return window['go']['main']['GranitApp']['ParseMarkdownTable'](arg1, arg2);
}

export function PublishToBlog(arg1, arg2) {
  return window['go']['main']['GranitApp']['PublishToBlog'](arg1, arg2);
}

export function PurgeFromTrash(arg1) {
  return window['go']['main']['GranitApp']['PurgeFromTrash'](arg1);
}

export function RefreshVault() {
  return window['go']['main']['GranitApp']['RefreshVault']();
}

export function RenameNote(arg1, arg2) {
  return window['go']['main']['GranitApp']['RenameNote'](arg1, arg2);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['main']['GranitApp']['RenameWorkspace'](arg1, arg2);
}

export function RestoreFromTrash(arg1) {
  return window['go']['main']['GranitApp']['RestoreFromTrash'](arg1);
}

export function RestoreNoteVersion(arg1, arg2) {
  return window['go']['main']['GranitApp']['RestoreNoteVersion'](arg1, arg2);
}

export function RunBot(arg1, arg2, arg3) {
  return window['go']['main']['GranitApp']['RunBot'](arg1, arg2, arg3);
}

export function RunDataviewQuery(arg1) {
  return window['go']['main']['GranitApp']['RunDataviewQuery'](arg1);
}

export function RunPluginCommand(arg1, arg2) {
  return window['go']['main']['GranitApp']['RunPluginCommand'](arg1, arg2);
}

export function SaveCanvas(arg1, arg2) {
  return window['go']['main']['GranitApp']['SaveCanvas'](arg1, arg2);
}

export function SaveDecryptedNote(arg1, arg2) {
  return window['go']['main']['GranitApp']['SaveDecryptedNote'](arg1, arg2);
}

export function SaveFlashcardProgress(arg1) {
  return window['go']['main']['GranitApp']['SaveFlashcardProgress'](arg1);
}

export function SaveHabits(arg1) {
  return window['go']['main']['GranitApp']['SaveHabits'](arg1);
}

export function SaveKanban(arg1) {
  return window['go']['main']['GranitApp']['SaveKanban'](arg1);
}

export function SaveNote(arg1, arg2) {
  return window['go']['main']['GranitApp']['SaveNote'](arg1, arg2);
}

export function SaveProjectsJSON(arg1) {
  return window['go']['main']['GranitApp']['SaveProjectsJSON'](arg1);
}

export function SaveSnippets(arg1) {
  return window['go']['main']['GranitApp']['SaveSnippets'](arg1);
}

export function SaveWorkspace(arg1, arg2) {
  return window['go']['main']['GranitApp']['SaveWorkspace'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['main']['GranitApp']['Search'](arg1);
}

export function SelectVaultDialog() {
  return window['go']['main']['GranitApp']['SelectVaultDialog']();
}

export function SetTheme(arg1) {
  return window['go']['main']['GranitApp']['SetTheme'](arg1);
}

export function ToggleBookmark(arg1) {
  return window['go']['main']['GranitApp']['ToggleBookmark'](arg1);
}

export function TogglePlugin(arg1) {
  return window['go']['main']['GranitApp']['TogglePlugin'](arg1);
}

export function ToggleTask(arg1, arg2) {
  return window['go']['main']['GranitApp']['ToggleTask'](arg1, arg2);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['GranitApp']['UpdateProject'](arg1, arg2);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['GranitApp']['UpdateSetting'](arg1, arg2);
}
