// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecent(arg1:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function CreateFromTemplate(arg1:number,arg2:string):Promise<string>;

export function CreateNote(arg1:string,arg2:string):Promise<string>;

export function DeleteNote(arg1:string):Promise<void>;

export function ExportAll():Promise<string>;

export function ExportHTML(arg1:string):Promise<string>;

export function ExportPDF(arg1:string):Promise<string>;

export function ExportText(arg1:string):Promise<string>;

export function GetAllSettings():Promise<Array<main.SettingItem>>;

export function GetAllTags():Promise<Array<main.TagEntryDTO>>;

export function GetBacklinkContext(arg1:string):Promise<Array<main.BacklinkContextEntry>>;

export function GetBookmarks():Promise<main.BookmarkFile>;

export function GetBotList():Promise<Array<main.BotInfo>>;

export function GetCalendarData(arg1:number,arg2:number):Promise<main.CalendarData>;

export function GetCommands():Promise<Array<main.CommandInfo>>;

export function GetFolderTree():Promise<main.FolderNode>;

export function GetGitBranch():Promise<string>;

export function GetGraphData(arg1:string):Promise<main.GraphData>;

export function GetKnownVaults():Promise<Array<main.VaultListEntry>>;

export function GetNote(arg1:string):Promise<main.NoteDetail>;

export function GetNotes():Promise<Array<main.NoteInfo>>;

export function GetNotesForTag(arg1:string):Promise<Array<main.NoteInfo>>;

export function GetOutline(arg1:string):Promise<Array<main.OutlineItem>>;

export function GetPlatform():Promise<string>;

export function GetTemplates():Promise<Array<main.TemplateInfo>>;

export function GetTheme():Promise<string>;

export function GetTrashItems():Promise<Array<main.TrashItemInfo>>;

export function GetVaultPath():Promise<string>;

export function GetVaultStats():Promise<main.VaultStatsData>;

export function GitCommit(arg1:string):Promise<string>;

export function GitDiff():Promise<string>;

export function GitLog():Promise<Array<string>>;

export function GitPull():Promise<string>;

export function GitPush():Promise<string>;

export function GitStatus():Promise<Array<string>>;

export function IsVaultOpen():Promise<boolean>;

export function MoveFile(arg1:string,arg2:string):Promise<string>;

export function OpenVault(arg1:string):Promise<void>;

export function PurgeFromTrash(arg1:string):Promise<void>;

export function RefreshVault():Promise<void>;

export function RenameNote(arg1:string,arg2:string):Promise<string>;

export function RestoreFromTrash(arg1:string):Promise<void>;

export function RunBot(arg1:number,arg2:string,arg3:string):Promise<main.BotResultData>;

export function SaveNote(arg1:string,arg2:string):Promise<void>;

export function Search(arg1:string):Promise<Array<main.SearchHit>>;

export function SelectVaultDialog():Promise<string>;

export function SetTheme(arg1:string):Promise<void>;

export function ToggleBookmark(arg1:string):Promise<boolean>;

export function ToggleTask(arg1:string,arg2:number):Promise<void>;

export function UpdateSetting(arg1:string,arg2:any):Promise<void>;
