// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecent(arg1:string):Promise<void>;

export function ChatWithAI(arg1:string):Promise<string>;

export function CreateBackup():Promise<string>;

export function CreateFolder(arg1:string):Promise<void>;

export function CreateFromTemplate(arg1:number,arg2:string):Promise<string>;

export function CreateNote(arg1:string,arg2:string):Promise<string>;

export function CreateProject(arg1:string):Promise<void>;

export function DecryptNote(arg1:string,arg2:string):Promise<string>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteCanvas(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function EncryptNote(arg1:string,arg2:string):Promise<void>;

export function EnsureJournalNote(arg1:string):Promise<main.NoteDetail>;

export function ExportAll():Promise<string>;

export function ExportHTML(arg1:string):Promise<string>;

export function ExportPDF(arg1:string):Promise<string>;

export function ExportText(arg1:string):Promise<string>;

export function GetAllSettings():Promise<Array<main.SettingItem>>;

export function GetAllTags():Promise<Array<main.TagEntryDTO>>;

export function GetAllTasks():Promise<Array<main.TaskItem>>;

export function GetAutoLinkSuggestions(arg1:string):Promise<Array<main.LinkSuggestionDTO>>;

export function GetBacklinkContext(arg1:string):Promise<Array<main.BacklinkContextEntry>>;

export function GetBookmarks():Promise<main.BookmarkFile>;

export function GetBotList():Promise<Array<main.BotInfo>>;

export function GetCalendarData(arg1:number,arg2:number):Promise<main.CalendarData>;

export function GetCanvas(arg1:string):Promise<string>;

export function GetCommands():Promise<Array<main.CommandInfo>>;

export function GetDailyBriefing():Promise<Record<string, any>>;

export function GetFlashcardProgress():Promise<string>;

export function GetFlashcards(arg1:string):Promise<Array<main.FlashcardDTO>>;

export function GetFolderTree():Promise<main.FolderNode>;

export function GetGitBranch():Promise<string>;

export function GetGraphData(arg1:string):Promise<main.GraphData>;

export function GetHabits():Promise<string>;

export function GetJournalNotes(arg1:number):Promise<Array<main.NoteDetail>>;

export function GetJournalPrompts():Promise<Array<Record<string, string>>>;

export function GetKanban():Promise<string>;

export function GetKnownVaults():Promise<Array<main.VaultListEntry>>;

export function GetMindMapData(arg1:string):Promise<string>;

export function GetNote(arg1:string):Promise<main.NoteDetail>;

export function GetNoteAtVersion(arg1:string,arg2:string):Promise<string>;

export function GetNoteDiff(arg1:string,arg2:string):Promise<string>;

export function GetNoteHistory(arg1:string):Promise<Array<main.NoteVersionDTO>>;

export function GetNotes():Promise<Array<main.NoteInfo>>;

export function GetNotesForTag(arg1:string):Promise<Array<main.NoteInfo>>;

export function GetOutline(arg1:string):Promise<Array<main.OutlineItem>>;

export function GetPlatform():Promise<string>;

export function GetPlugins():Promise<Array<main.PluginInfoDTO>>;

export function GetProjectTasks(arg1:string):Promise<Array<main.TaskItem>>;

export function GetProjects():Promise<Array<main.Project>>;

export function GetQuizQuestions(arg1:string):Promise<Array<main.QuizQuestionDTO>>;

export function GetRecurringTasks():Promise<Array<main.RecurringTaskDTO>>;

export function GetSmartConnections(arg1:string):Promise<Array<main.SmartConnectionDTO>>;

export function GetSnippets():Promise<Array<main.SnippetDTO>>;

export function GetTemplates():Promise<Array<main.TemplateInfo>>;

export function GetTheme():Promise<string>;

export function GetTimeline():Promise<Array<main.TimelineEntryDTO>>;

export function GetTrashItems():Promise<Array<main.TrashItemInfo>>;

export function GetVaultPath():Promise<string>;

export function GetVaultStats():Promise<main.VaultStatsData>;

export function GetWritingFeedback(arg1:string):Promise<string>;

export function GitCommit(arg1:string):Promise<string>;

export function GitDiff():Promise<string>;

export function GitLog():Promise<Array<string>>;

export function GitPull():Promise<string>;

export function GitPush():Promise<string>;

export function GitStatus():Promise<Array<string>>;

export function IsNoteEncrypted(arg1:string):Promise<boolean>;

export function IsVaultOpen():Promise<boolean>;

export function ListBackups():Promise<Array<main.BackupInfoDTO>>;

export function ListCanvases():Promise<Array<string>>;

export function ListWorkspaces():Promise<Array<string>>;

export function LoadWorkspace(arg1:string):Promise<string>;

export function MoveFile(arg1:string,arg2:string):Promise<string>;

export function OpenVault(arg1:string):Promise<void>;

export function ParseMarkdownTable(arg1:string,arg2:number):Promise<main.TableDataDTO>;

export function PublishToBlog(arg1:string,arg2:string):Promise<string>;

export function PurgeFromTrash(arg1:string):Promise<void>;

export function RefreshVault():Promise<void>;

export function RenameNote(arg1:string,arg2:string):Promise<string>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<void>;

export function RestoreFromTrash(arg1:string):Promise<void>;

export function RestoreNoteVersion(arg1:string,arg2:string):Promise<void>;

export function RunBot(arg1:number,arg2:string,arg3:string):Promise<main.BotResultData>;

export function RunDataviewQuery(arg1:string):Promise<Array<Record<string, any>>>;

export function RunPluginCommand(arg1:string,arg2:string):Promise<string>;

export function SaveCanvas(arg1:string,arg2:string):Promise<void>;

export function SaveDecryptedNote(arg1:string,arg2:string):Promise<void>;

export function SaveFlashcardProgress(arg1:string):Promise<void>;

export function SaveHabits(arg1:string):Promise<void>;

export function SaveKanban(arg1:string):Promise<void>;

export function SaveNote(arg1:string,arg2:string):Promise<void>;

export function SaveProjectsJSON(arg1:string):Promise<void>;

export function SaveSnippets(arg1:string):Promise<void>;

export function SaveWorkspace(arg1:string,arg2:string):Promise<void>;

export function Search(arg1:string):Promise<Array<main.SearchHit>>;

export function SelectVaultDialog():Promise<string>;

export function SetTheme(arg1:string):Promise<void>;

export function ToggleBookmark(arg1:string):Promise<boolean>;

export function TogglePlugin(arg1:string):Promise<void>;

export function ToggleTask(arg1:string,arg2:number):Promise<void>;

export function UpdateProject(arg1:number,arg2:string):Promise<void>;

export function UpdateSetting(arg1:string,arg2:any):Promise<void>;
